added root check

diff --git a/bin/init.d/litus b/bin/init.d/litus
--- a/bin/init.d/litus
+++ b/bin/init.d/litus
@@ -29,6 +29,15 @@ HAVE_PRINTERS=0
 set +e
 
 ##
+# Quit if we're not root or $USER
+#
+
+if [[ "$EUID" != "0" ]] && [[ $(whoami) != "$USER" ]]; then
+    echo "You're not root or $USER, aborting..." >&2
+    exit 5
+fi
+
+##
 # Load init helper functions
 #
 
